In [19]:
from vislearnlabpy.embeddings.generate_embeddings import EmbeddingGenerator, EmbeddingConfig
from vislearnlabpy.embeddings.embedding_store import EmbeddingStore
from vislearnlabpy.embeddings.similarity_generator import SimilarityGenerator
from vislearnlabpy.embeddings.similarity_utils import text_image_sims_from_stores, csv_to_text_pairs, plot_rdm, compute_rdm
import os
import numpy as np
import pandas as pd


An example of using the embedding store to get similarity scores between embeddings. First choose your model to generate embeddings.

In [20]:
from vislearnlabpy.models.hf_model import MODEL_PRESETS
MODEL_PRESETS.keys()

dict_keys(['clip', 'clip-large', 'clip-hf', 'clip-hf-large', 'dinov3-base', 'dinov3', 'dinov3-babyview', 'dinov3-small', 'dinov2', 'dinov2-base', 'dino_say_vitb14', 'dino_s_vitb14', 'dino_a_vitb14', 'dino_y_vitb14', 'dino_sfp_vitb14', 'dino_imagenet100_vitb14', 'dino_imagenet10_vitb14', 'dino_imagenet1_vitb14', 'dino_kinetics-200h_vitb14', 'dino_ego4d-200h_vitb14', 'dino_say_resnext50', 'dino_s_resnext50', 'dino_a_resnext50', 'dino_y_resnext50', 'dino_sfp_resnext50', 'dino_say_vitl16', 'dino_s_vitl16', 'dino_a_vitl16', 'dino_y_vitl16', 'dino_say_vitb16', 'dino_s_vitb16', 'dino_a_vitb16', 'dino_y_vitb16', 'dino_say_vits16', 'dino_s_vits16', 'dino_a_vits16', 'dino_y_vits16', 'mugs_say_vitl16', 'mugs_s_vitl16', 'mugs_a_vitl16', 'mugs_y_vitl16', 'mugs_say_vitb16', 'mugs_s_vitb16', 'mugs_a_vitb16', 'mugs_y_vitb16', 'mugs_say_vits16', 'mugs_s_vits16', 'mugs_a_vits16', 'mugs_y_vits16', 'mae_say_vitl16', 'mae_s_vitl16', 'mae_a_vitl16', 'mae_y_vitl16', 'mae_say_vitb16', 'mae_s_vitb16', 'mae_a_vitb16', 'mae_y_vitb16', 'mae_say_vits16', 'mae_s_vits16', 'mae_a_vits16', 'mae_y_vits16'])

In [21]:
config = EmbeddingConfig()
generator = EmbeddingGenerator.from_model("clip-hf", device="cpu", output_type="doc")

Loading weights: 100%|██████████| 398/398 [00:00<00:00, 64760.56it/s]
CLIPModel LOAD REPORT from: openai/clip-vit-base-patch32
Key                                  | Status     |  |
-------------------------------------+------------+--+-
vision_model.embeddings.position_ids | UNEXPECTED |  |
text_model.embeddings.position_ids   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Getting the similarity scores for all of the images against one another.

In [22]:
from pathlib import Path
generator.generate_image_embeddings(input_dir="../input", output_path=".")
image_embedding_store = EmbeddingStore.from_doc("image_embeddings/clip_image_embeddings_doc.docs")
sim_df = image_embedding_store.retrieve_similarities()
sim_df.head()

Found 7 images in ../input

Loading weights: 100%|██████████| 398/398 [00:00<00:00, 64612.67it/s]
CLIPModel LOAD REPORT from: openai/clip-vit-base-patch32
Key                                  | Status     |  |
-------------------------------------+------------+--+-
vision_model.embeddings.position_ids | UNEXPECTED |  |
text_model.embeddings.position_ids   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
1it [00:00, 3368.92it/s]ngs:   0%|          | 0/7 [00:00<?, ?it/s]
1it [00:00, 7530.17it/s]ngs:  14%|█▍        | 1/7 [00:00<00:00,  6.38it/s]
1it [00:00, 5874.38it/s]ngs:  29%|██▊       | 2/7 [00:00<00:00,  7.78it/s]
1it [00:00, 4809.98it/s]ngs:  43%|████▎     | 3/7 [00:00<00:00,  5.64it/s]
1it [00:00, 7096.96it/s]
1it [00:00, 7294.44it/s]ngs:  71%|███████▏  | 5/7 [00:00<00:00,  8.57it/s]
1it [00:00, 8192.00it/s]
Calculating clip embeddings: 100%|██████████| 7/7 [00:00<00:00,  8.93it/s]
WARNING:root:local_cache is not supported for "file" protocol
WARNING:root:local_cache is not supported for "file" protocol

/Users/vislearnlab/miniconda3/envs/vllpy/lib/python3.11/site-packages/rich/live.py:256: UserWarning: install
"ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

,cosine_similarity,text1,text2
0,0.6177,/Users/vislearnlab/Documents/vllpy/examples/in...,/Users/vislearnlab/Documents/vllpy/examples/in...
1,0.8708,/Users/vislearnlab/Documents/vllpy/examples/in...,/Users/vislearnlab/Documents/vllpy/examples/in...
2,0.6311,/Users/vislearnlab/Documents/vllpy/examples/in...,/Users/vislearnlab/Documents/vllpy/examples/in...
3,0.4734,/Users/vislearnlab/Documents/vllpy/examples/in...,/Users/vislearnlab/Documents/vllpy/examples/in...
4,0.5063,/Users/vislearnlab/Documents/vllpy/examples/in...,/Users/vislearnlab/Documents/vllpy/examples/in...

## VisVocab testing

In [ ]:
PROJECT_PATH = '/Users/vislearnlab/Documents/visual-precision'
input_csv_df = pd.read_csv(os.path.join(
                PROJECT_PATH, "data", "metadata", "level-imagepair_data.csv"
            ))
input_csv_df.head()

,Unnamed: 0,X,text1,text2,AoA_Est_Word1,AoA_Est_Word2,recognizability_word1,recognizability_word2,AoA_Word1_WB,AoA_Word2_WB,cor,animacy,wordPairing,section
0,1,1.0,turkey,swan,3.95,6.317630,0.7140,0.8570,28.0,NaN,0.810027,1,easy,sample1
1,2,2.0,turtle,horse,4.17,4.150000,0.8460,0.9375,24.0,22.0,0.829944,1,easy,sample1
2,3,3.0,cheese,mud,4.33,4.050000,0.4375,0.7500,19.0,NaN,0.807121,0,easy,sample1
3,4,4.0,squirrel,eagle,4.44,5.830000,0.7140,0.9330,26.0,NaN,0.829296,1,easy,sample1
4,5,5.0,potato,glasses,4.84,4.346085,1.0000,1.0000,26.0,25.0,0.748707,0,easy,sample1

In [ ]:
PROJECT_PATH = '/Users/vislearnlab/Documents/visvocab'
input_csv_df = pd.read_csv(os.path.join(
                PROJECT_PATH, "data", "metadata", "level-imagepair_data.csv"
            ))
input_csv_df.head()

Since this file does not contain image1 and image2 columns, it attempts a direct mapping between the text1 and text2 columns to images in the provided directory. Alternatively, you can add image1 and image2 columns with the filenames.

In [ ]:
config = EmbeddingConfig(device="cpu", output_type="doc")
generator = EmbeddingGenerator(config=config)
# path to the csv with the trial metadata
input_csv = os.path.join(
                PROJECT_PATH, "data", "metadata", "level-imagepair_data.csv"
            )
# path to the images
input_path = os.path.join(PROJECT_PATH, "stimuli", "lookit", "exp1", "img")

In [ ]:
generator.generate_image_embeddings(output_path="visvocab", input_csv=input_csv, input_dir=input_path, batch_size=100, id_column=None)
image_embedding_store = EmbeddingStore.from_doc("visvocab/image_embeddings/clip_image_embeddings_doc.docs")
text_embedding_store = EmbeddingStore.from_doc("visvocab/text_embeddings/clip_text_embeddings_doc.docs")

Checking if embeddings look good.

In [ ]:
docs, scores = image_embedding_store.search_store(text_query="turkey")
print(docs.text)
print(scores)

Retrieving cosine similarities by default.

In [ ]:
specific_sim_pairs = csv_to_text_pairs(input_csv)
text_image_sims_from_stores(text_embedding_store, image_embedding_store, "output/sims/similarities.csv", specific_sim_pairs)

RDM

In [ ]:
rdm = compute_rdm(np.stack(image_embedding_store.EmbeddingList.embedding), method="cosine")
plot_rdm("output/sims", rdm)